### ISSUE TITLE
Aggregate: Error in match.fun(FUN)

### ISSUE THREAD

**Issue by liptzin** [wviechtb/metafor#42] opened 2021-01-28 20:32 UTC
## Classification:
Bug Report
## Summary

Summary of the problem.
I was excited to see the addition of the aggregate function to metafor.  However, I'm getting the error that is supposed to be for if you use an object that isn't an escalc class. 

## Reproducible Example (if applicable)

# use this for posting code (if applicable)
```
> dat
   shi_site_id      yi     vi 
1       CAAB01  0.7121 0.3445 
2       CAAB01  1.0661 0.2727 
3       CAMB01 -0.4415 0.0875 
4       CAON03  0.3718 0.0468 
5       CAON03  0.1676 0.0001 
6       CAON03  0.2924 0.0122 
7       CAON03  0.4170 0.0168 
8       MXPU01 -0.0829 0.2257 
9       USAL01  0.1295 0.0467 
10      USAL01  0.3567 0.0130 
11      USAL01  0.2496 0.0524 
12      USAL01  0.2262 0.0388 
13      USAL01  0.0045 0.0451 
14      USAL01  0.2317 0.0115 
15      USAL01  0.1106 0.0217 
16      USAL01  0.0872 0.0081 
17      USCO04  0.2072 0.0116 
18      USCO04 -0.2550 0.0781 
19      USDE01  0.1937 0.0051 
> class(dat)
[1] "escalc"     "data.frame"

agg<-aggregate(dat,cluster=shi_site_id)
```
# use this for posting output (if applicable)
Error in match.fun(FUN) : argument "FUN" is missing, with no default
```

## Notes

Since aggregate is relatively new, I updated my version of metafor and then downloaded the development version from Github. I also tried  
agg<-metafor::aggregate(dat,cluster="shi_site_id")
Error: 'aggregate' is not an exported object from 'namespace:metafor'
I used the find_funs function from https://sebastiansauer.github.io/finds_funs/ and got this output
> find_funs("aggregate")
# A tibble: 7 x 3
  package_name builtin_pckage loaded
  <chr>        <lgl>          <lgl> 
1 Biobase      FALSE          FALSE 
2 metafor      FALSE          TRUE  
3 raster       FALSE          FALSE 
4 S4Vectors    FALSE          FALSE 
5 sf           FALSE          FALSE 
6 sp           FALSE          FALSE 
7 stats        TRUE           TRUE  


## sessionInfo()
```
Post output of `sessionInfo()` below:
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] robumeta_2.0      ggpubr_0.2.5      magrittr_1.5      data.table_1.12.8 metafor_2.5-74   
 [6] Matrix_1.2-18     forcats_0.5.0     stringr_1.4.0     dplyr_1.0.2       purrr_0.3.3      
[11] tidyr_1.0.2       tibble_3.0.0      ggplot2_3.3.0     tidyverse_1.3.0   readr_1.3.1      
[16] readxl_1.3.1     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4        lubridate_1.7.4   lattice_0.20-40   prettyunits_1.1.1 ps_1.3.2         
 [6] rprojroot_1.3-2   assertthat_0.2.1  digest_0.6.25     R6_2.4.1          cellranger_1.1.0 
[11] backports_1.1.5   reprex_0.3.0      httr_1.4.1        pillar_1.4.3      rlang_0.4.8      
[16] curl_4.3          rstudioapi_0.11   callr_3.4.3       labeling_0.3      munsell_0.5.0    
[21] broom_0.5.5       compiler_3.6.1    modelr_0.1.6      pkgconfig_2.0.3   pkgbuild_1.0.6   
[26] clipr_0.7.0       tidyselect_1.1.0  gridExtra_2.3     fansi_0.4.1       crayon_1.3.4     
[31] dbplyr_1.4.2      withr_2.1.2       grid_3.6.1        nlme_3.1-145      jsonlite_1.6.1   
[36] gtable_0.3.0      lifecycle_0.2.0   DBI_1.1.0         scales_1.1.0      cli_2.0.2        
[41] stringi_1.4.6     farver_2.0.3      ggsignif_0.6.0    fs_1.4.0          remotes_2.2.0    
[46] xml2_1.2.5        ellipsis_0.3.0    generics_0.0.2    vctrs_0.3.4       cowplot_1.0.0    
[51] tools_3.6.1       glue_1.3.2        hms_0.5.3         processx_3.4.2    colorspace_1.4-1 
[56] rvest_0.3.5       haven_2.2.0   
```

**Comment by wviechtb** [comment] 2021-01-28 22:04
See the help file: https://wviechtb.github.io/metafor/reference/aggregate.escalc.html where this is documented. If you pass a regular data frame to `aggregate()`, then this gets passed to `aggregate.data.frame()`, not `aggregate.escalc()`. The former comes from the `stats` package.

**Comment by liptzin** [comment] 2021-01-28 22:34
Thanks for your response. I was hoping I didn't clearly make a mistake that is so explicitly described in your help file, but I don't think that is the root of the problem. To simplify things, I didn't include the original data, only the important columns of the output from escalc. If it is important to have ieiunw, then I can share that too. 

dat<-escalc(measure='ROM', m2i=Mc , sd2i=Sc, n2i=Nc, m1i=Me, sd1i=Se, n1i=Ne,var.names=c("yi","vi"),data=ieiunw)
dat<-dat[,c(1,16,17)]
class(dat)
[1] "escalc"     "data.frame"
agg<-aggregate(dat,cluster="shi_site_id")
Error in match.fun(FUN) : argument "FUN" is missing, with no default

I don't understand why aggregate is treating dat like a data frame instead of an escalc object given the results of class(dat)

**Comment by wviechtb** [comment] 2021-01-29 08:30
Please provide fully reproducible examples. For example:

    dat <- structure(list(shi_site_id = c("CAAB01", "CAAB01", "CAMB01", "CAON03", "CAON03", "CAON03", "CAON03", "MXPU01", "USAL01", "USAL01", "USAL01", "USAL01", "USAL01", "USAL01", "USAL01", "USAL01", "USCO04", "USCO04", "USDE01"), yi = structure(c(0.7121, 1.0661, -0.4415, 0.3718, 0.1676, 0.2924, 0.417, -0.0829, 0.1295, 0.3567, 0.2496, 0.2262, 0.0045, 0.2317, 0.1106, 0.0872, 0.2072, -0.255, 0.1937 ), measure = "ROM"), vi = c(0.3445, 0.2727, 0.0875, 0.0468, 1e-04, 0.0122, 0.0168, 0.2257, 0.0467, 0.013, 0.0524, 0.0388, 0.0451, 0.0115, 0.0217, 0.0081, 0.0116, 0.0781, 0.0051)), row.names = c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19"), class = c("escalc", "data.frame"), digits = c(est = 4, se = 4, test = 4, pval = 4, ci = 4, var = 4, sevar = 4, fit = 4, het = 4), yi.names = "yi", vi.names = "vi")
    dat <- escalc(measure="ROM", yi=yi, vi=vi, data=dat)
    dat
    agg <- aggregate(dat, cluster=shi_site_id, rho=0.7)
    agg

And that works without any problems. Have you actually loaded the 'devel' version in your last attempt? Seems like you have loaded the CRAN version, which does not have `aggregate.escalc()`. Then `aggregate(dat, cluster="shi_site_id")` again calls `aggregate.data.frame()` (since that is the second class of `dat` and there is no `aggregate.escalc()` method).

Also, the clustering variable should be supplied without quotes. Finally, you need to specify additional arguments, like `rho`.

**Comment by wviechtb** [comment] 2021-02-16 15:15
Closing because this is presumably resolved.

**Closed by wviechtb** 2021-02-16 15:15 UTC
